version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    env_file:
      - ./config/.env
    ports:
      - 3000:3000
    volumes:
      - app-data:/var/app/app-data
  postgres-dev:
    container_name: postgres-dev
    build:
      context: .
      dockerfile: ./docker/postgres.dev.dockerfile
    restart: always
    ports:
      - 5410:5432
    volumes:
      - postgres-data:/var/lib/postgresql/dev-data
  postgres-test:
    container_name: postgres-test
    build:
      context: .
      dockerfile: ./docker/postgres.test.dockerfile
    restart: always
    ports:
      - 5420:5432
    volumes:
      - postgres-data:/var/lib/postgresql/test-data
volumes:
  app-data:
  postgres-data:
